#ifndef BILBO_GENERICS_H
#define BILBO_GENERICS_H

#define TUNE_RANGE_NULL 0
#define TUNE_RANGE_PLACEHOLDER 1
#define TUNE_RANGE_BASS 2
#define TUNE_RANGE_GUITAR 3
#define TUNE_RANGE_HIGH 4

#endif